ThreeStars = ["Raven Bow",
              "Sharpshooter's Oath",
              "Slingshot", "Emerald Orb",
              "Magic Guide",
              "Thrilling Tales of Dragon Slayers",
              "Bloodtainted Greatsword",
              "Debate Club",
              "Ferrous Shadow",
              "Black Tassel",
              "Cool Steel",
              "Harbinger of Dawn",
              "Skyrider Sword"]

FourStars = ["Favonious Warbow",
             "Rust",
             "Sacrificial Bow",
             "The Stringless",
             "Eye of Perception",
             "Favonious Codex",
             "Sacrificial Fragments",
             "The Widsith",
             "Favonious Greatsword",
             "Rainslasher",
             "Sacrificial Greatsword",
             "The Bell",
             "Dragon's Bane",
             "Favonious Lance",
             "Favonious Sword",
             "Lion's Roar",
             "Sacrificial Sword",
             "The Flute",
             "Sayu",
             "Chongyun",
             "Diona",
             "Rosaria",
             "Kujou Sara",
             "Beidou",
             "Fischl",
             "Razor",
             "Gorou",
             "Ningguang",
             "Noelle",
             "Barbara",
             "Xingqiu",
             "Bennett",
             "Xinyan",
             "Thoma",
             "Yanfei",
             "Sucrose",
             "Xiangling",
             "Yun Jin"]

FiveStarsStandard = ["Jean", "QIQI LMAO", "Keking", "Mona", "Diluc"]
